# Generated by Django 5.2.7 on 2026-01-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='erp_status',
            field=models.CharField(blank=True, choices=[('sending', 'Enviando'), ('sent', 'Enviado'), ('confirmed', 'Confirmado'), ('error', 'Erro')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('erp_sent', 'Enviado ao ERP'), ('erp_confirmed', 'Confirmado no ERP'), ('erp_error', 'Erro no ERP')], default='pending', max_length=32),
        ),
    ]
