# Generated by Django 5.2.7 on 2026-03-26 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_alter_pedido_erp_status_alter_pedido_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='erp_status',
            field=models.CharField(blank=True, choices=[('received', 'Recebido'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('confirmed', 'Confirmado'), ('error', 'Erro')], max_length=32, null=True),
        ),
    ]
