# Generated by Django 5.2.7 on 2026-04-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0004_alter_pedido_erp_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estoque_baixado',
            field=models.BooleanField(default=False),
        ),
    ]
