# Generated by Django 5.2.7 on 2026-04-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0006_alter_pedido_erp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='erp_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pendente'), ('received', 'Recebido'), ('paid', 'Pago'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('return', 'Devolução'), ('returned', 'Devolvido'), ('error', 'Erro')], max_length=32, null=True),
        ),
    ]
