# Generated by Django 5.2.7 on 2026-04-02 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0007_alter_pedido_erp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='erp_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pendente'), ('received', 'Recebido'), ('paid', 'Pago'), ('sending', 'Enviando'), ('sent', 'Enviado'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado'), ('return', 'Devolução'), ('return_refusal', 'Devolução negada'), ('returned', 'Devolvido'), ('error', 'Erro')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('paid', 'Pago'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado'), ('refusal', 'Reembolso negado'), ('erp_sent', 'Enviado ao ERP'), ('erp_confirmed', 'Confirmado no ERP'), ('erp_error', 'Erro no ERP')], default='pending', max_length=32),
        ),
    ]
