# Generated by Django 5.2.7 on 2026-04-07 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0008_alter_pedido_erp_status_alter_pedido_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao_reembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(max_length=50)),
                ('feedback', models.TextField(blank=True, max_length=300, null=True)),
                ('evidencias', models.FileField(upload_to='evidencias-devolucao/')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('approved', 'Aprovado'), ('rejected', 'Rejeitado'), ('completed', 'Concluído')], default='pending', max_length=20)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_reembolso', to='pagamentos.pedido')),
            ],
        ),
    ]
