# Generated by Django 5.2.7 on 2026-04-17 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_comerce', '0018_alter_produto_imagem_alter_produto_preco_promocional'),
        ('pagamentos', '0009_solicitacao_reembolso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoitem',
            old_name='produto_id',
            new_name='produto_id_string',
        ),
        migrations.AddField(
            model_name='pedidoitem',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='e_comerce.produto'),
        ),
    ]
