# Generated by Django 5.2.7 on 2026-04-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0010_rename_produto_id_pedidoitem_produto_id_string_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='data_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de envio'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Código de rastreio'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='tracking_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL de rastreio'),
        ),
    ]
