# Generated by Django 5.2.7 on 2026-04-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0011_pedido_data_envio_pedido_tracking_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total_com_frete',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='valor_frete',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
