# Generated by Django 5.2.7 on 2026-02-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0002_carrinho_session_key_carrinho_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrinho',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
