# Generated by Django 5.2.7 on 2026-02-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0003_carrinho_atualizado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrinho',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True),
        ),
    ]
