# Generated by Django 5.2.7 on 2026-02-26 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrinho', '0004_alter_carrinho_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcarrinho',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
