# Generated by Django 5.2.7 on 2026-02-10 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_de_usuarios', '0003_alter_endereco_options_alter_endereco_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='estado',
        ),
        migrations.AddField(
            model_name='endereco',
            name='padrao',
            field=models.BooleanField(default=False),
        ),
    ]
