# Generated by Django 5.2.7 on 2026-02-23 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_de_usuarios', '0005_endereco_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='endereco',
            constraint=models.UniqueConstraint(condition=models.Q(('padrao', True)), fields=('usuario',), name='unique_default_per_user'),
        ),
    ]
