# Generated by Django 5.2.7 on 2026-03-05 18:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_de_usuarios', '0006_endereco_unique_default_per_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='endereco',
            index=models.Index(fields=['usuario', 'padrao'], name='cadastro_de_usuario_c8d64b_idx'),
        ),
    ]
