# Generated by Django 5.2.7 on 2026-04-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_de_usuarios', '0007_endereco_cadastro_de_usuario_c8d64b_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
