# Generated by Django 5.2.7 on 2025-11-29 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_comerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['-criado'], 'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
    ]
