# Generated by Django 5.2.7 on 2025-12-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_comerce', '0002_alter_produto_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='ofertas_do_dia',
            field=models.BooleanField(default=False, verbose_name='Ofertas do dia'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/%Y/%m/%d', verbose_name='Imagem'),
        ),
    ]
