# Generated by Django 5.2.7 on 2025-12-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_comerce', '0003_produto_ofertas_do_dia_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/%/%/%d', verbose_name='Imagem'),
        ),
    ]
