# Generated by Django 5.2.7 on 2025-12-04 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_comerce', '0004_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
    ]
