# Generated by Django 5.2.7 on 2025-12-04 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_comerce', '0007_alter_produto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='slug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_comerce.category', verbose_name='slug'),
        ),
    ]
