# Generated by Django 5.2.7 on 2025-12-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_comerce', '0009_alter_produto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='erp_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='ERP ID'),
        ),
        migrations.AddField(
            model_name='produto',
            name='last_synced',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última sincronização'),
        ),
        migrations.AddField(
            model_name='produto',
            name='remote_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Preço remoto'),
        ),
        migrations.AddField(
            model_name='produto',
            name='remote_stock',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estoque remoto'),
        ),
    ]
