# Generated by Django 5.2.7 on 2026-01-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_comerce', '0010_produto_erp_id_produto_last_synced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='Imagem remota'),
        ),
    ]
