# Generated by Django 5.2.7 on 2026-01-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_comerce', '0011_produto_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_promocional',
            field=models.FloatField(default=0, verbose_name='Preço promocional'),
        ),
    ]
