# Generated by Django 5.2.7 on 2026-03-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_comerce', '0012_produto_preco_promocional'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['category', 'disponivel'], name='e_comerce_p_categor_778fff_idx'),
        ),
    ]
