# Generated by Django 5.2.7 on 2026-03-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_comerce', '0013_produto_e_comerce_p_categor_778fff_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['ofertas_do_dia', 'disponivel'], name='e_comerce_p_ofertas_84747e_idx'),
        ),
    ]
