# Generated by Django 5.2.7 on 2026-03-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_comerce', '0015_avaliacao_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao_produto',
            name='media_avaliacao_prod',
            field=models.FloatField(default=0),
        ),
    ]
