# Generated by Django 5.2.7 on 2026-03-31 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_comerce', '0016_avaliacao_produto_media_avaliacao_prod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao_produto',
            name='media_avaliacao_prod',
        ),
    ]
