# Generated by Django 5.2.7 on 2026-04-15 13:15

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_comerce', '0017_remove_avaliacao_produto_media_avaliacao_prod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='produtos/%Y/%m/%d/', verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_promocional',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Preço promocional'),
        ),
    ]
