# Generated by Django 5.2.7 on 2026-05-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_comerce', '0018_alter_produto_imagem_alter_produto_preco_promocional'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
