# Generated by Django 5.2.7 on 2026-06-29 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_comerce', '0020_produto_sku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto_imagens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fotos', models.ImageField(blank=True, null=True, upload_to='produtos/%Y/%m/%d/', verbose_name='Imagens')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carrosel', to='e_comerce.produto')),
            ],
        ),
    ]
