# Generated by Django 5.2.7 on 2026-06-29 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_comerce', '0021_produto_imagens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto_imagens',
            new_name='ProdutoImagens',
        ),
        migrations.RenameField(
            model_name='produtoimagens',
            old_name='fotos',
            new_name='foto',
        ),
    ]
