# Generated by Django 5.2.7 on 2026-04-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=35, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('texto', models.CharField(max_length=400, verbose_name='Área de contato')),
            ],
            options={
                'verbose_name': 'Contato',
            },
        ),
    ]
